name: weather_app
description: A Flutter-based weather application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Stable SDK range as of May 2025

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1  # For making API requests
  intl: ^0.19.0 # For date and time formatting
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true